build_name: "{{ inventory_file }}"
current_build_value: "{{ lookup('current_build', build_name, 'get') }}"
files_dir: "{{ lookup('env', 'ANSIBLE_FILES')|default('/data/ansible/aca-builds/files', true) }}"
acting_user: "{{ lookup('env', 'USER') }}"
