    - debug: msg="Config dir is {{ config_dir }}"

    - name: Copy config files
      synchronize: src="{{ config_dir }}/" dest="{{ base_dir }}/conf/" rsync_opts=--no-group,--omit-dir-times,--exclude=.svn perms=no

    - name: Reload apache
      command: sudo /usr/local/apache/bin/ap-reload --restart
