    - debug: msg="Build name is {{ build_name }}"
    - debug: msg="Files dir is {{ files_dir }}"
    - debug: msg="Current build is {{ current_build_value }}"

    - name: Create directory for the next build
      file: group="{{ file_group }}" mode="2775" state="directory" path="{{ base_dir }}/builds/{{ current_build_value }}"

    - name: Copy config files
      synchronize: src="{{ files_dir }}/{{ build_name }}/" dest="{{ base_dir }}/builds/{{ current_build_value }}/" rsync_opts=--no-group,--omit-dir-times,--exclude=.svn perms=no

    - name: Install tools
      with_dict: "{{ install_requires }}"
      git: repo={{ item.value }} version=master dest={{ base_dir }}/builds/{{ current_build_value }}/{{ item.key }} accept_hostkey=yes

    - name: Build statics
      shell: perl {{ base_dir }}/builds/{{ current_build_value }}/corral/bin/bundle_for_config.pl --config={{ base_dir }}/builds/{{ current_build_value }}/solstice_config.xml --static-hosts={{ groups['catalyst-static-server']|join(',') }}
      register: statics_cfg
      run_once: true

    - debug: msg="Build statics output is {{ statics_cfg.stdout }}"

    - name: Update statics config
      shell: perl {{ base_dir }}/builds/{{ current_build_value }}/hostconfig/bin/update_statics_config.pl --config-file={{ base_dir }}/builds/{{ current_build_value }}/hostconfig/config.xml {{ statics_cfg.stdout }}

    - name: Link apps to the current build
      file: group="{{ file_group }}" src="{{ base_dir }}/builds/{{current_build_value}}" dest="{{ base_dir }}/apps" state="link" force="yes"

    - name: Reload apache
      command: sudo /usr/local/apache/bin/ap-reload --restart
