    # Copy over the mysql files that are a pain to build on the hosts
    - name: Copy mysql libraries
      synchronize: src="{{ files_dir }}/mysql-libs" dest="{{ base_dir }}/" rsync_opts=--omit-dir-times,--exclude=.svn perms=no
      when: database_type is not defined or database_type == "mysql"


