    - debug: msg = "the build_name is {{ build_name }}"
    - debug: msg = "the files_dir is {{ files_dir }}"
    - debug: msg = "the current build is {{ current_build_value }}"

    - name: Ensure the base directory exists
      file: group="{{ file_group }}" mode="2775" state="directory" path="{{ base_dir }}/"

    - name: Copy keytab file
      copy: src="{{ files_dir }}/{{ keytab_file }}" dest="{{ base_dir }}/{{ keytab_file }}" group="{{ file_group }}" mode="0664"
      when: keytab_file is defined

    - name: Ensure builds directory exists
      file: group="{{ file_group }}" mode="2775" state="directory" path="{{ base_dir }}/builds"

    - name: Ensure log directory exists
      file: group="{{ log_group }}" mode="2775" state="directory" path="{{ base_dir }}/logs"

    - name: Ensure static content directory exists
      file: group="{{ file_group }}" mode="2775" state="directory" path="{{ base_dir }}/static"

    - name: Point apache configuration to the right place
      file: group="{{ file_group }}" src="{{ base_dir }}/live/apache_config/apache-global" dest="{{ apache_config_path | default('/data/conf/apache-global') }}" state="link" force="yes"

    - include: database-prereqs.yml

    - name: Copy node and less
      synchronize: src="{{ files_dir }}/node-libs" dest="{{ base_dir }}/" rsync_opts=--omit-dir-times,--exclude=.svn perms=no

    # assuming certs aren't changing between releases?
    - name: Ensure certs directory exists
      file: group="{{ file_group }}" mode="2775" state="directory" path="{{ base_dir }}/certs"

    - copy: src="{{ files_dir }}/certs/ca-bundle.crt" dest="{{ base_dir }}/certs/ca-bundle.crt" group="{{ file_group }}"
    - copy: src="{{ files_dir }}/certs/{{ webservice_client_cert_name }}" dest="{{ base_dir }}/certs/{{ webservice_client_cert_name }}" group="{{ file_group }}"
      when: webservice_client_cert_name != "" and webservice_client_cert_name is defined
    - copy: src="{{ files_dir }}/certs/{{ webservice_client_key_name }}" dest="{{ base_dir }}/certs/{{ webservice_client_key_name }}" group="{{ file_group }}"
      when: webservice_client_key_name != "" and webservice_client_key_name is defined

# Something should go here that determines it's build #{{current_build_value}}.  A lookup?

    - name: Create directory for the next build
      file: group="{{ file_group }}" mode="2775" state="directory" path="{{ base_dir }}/builds/{{ current_build_value }}"
