- set_fact:
    nagios_result: "{{ lookup('nagios_register', nagios_registration_oauth_key, nagios_registration_oauth_secret, nagios_registration_server, inventory_file, groups) }}"
- debug: msg="{{ nagios_result }}"
