- set_fact:
    nagios_tmp_dir: "{{ base_dir }}/nagios_{{ acting_user }}"

- name: Create tmp directory for nagios files
  file: state="directory" path="{{ nagios_tmp_dir }}" mode="700"

- name: Create tmp directory for nagios scripts
  file: state="directory" path="{{ nagios_tmp_dir }}/scripts" mode="700"

- name: Create the scp wrapper to add content to the acamon account
  template: src="templates/nagios/nagios_scp" dest="{{ nagios_tmp_dir }}/nagios_scp" mode="700"

- name: Create the script to add the public key to the acamon account
  template: src="templates/nagios/add_public_key" dest="{{ nagios_tmp_dir }}/add_public_key" mode="700"

- name: Set the authorized key for acamon
  command: "{{ nagios_tmp_dir }}/add_public_key"

- include: includes/nagios/create_default_scripts.yml

- include: includes/nagios/create_catalyst_scripts.yml
  when: "catalyst-app-server" in group_names

- name: Remove nagios tmp directory
  file: state="absent" path="{{ nagios_tmp_dir}}"

- set_fact:
    nagios_result: "{{ lookup('nagios_register') }}"
- debug: msg="{{ nagios_result }}"
