- hosts: django-app-server
  vars:
    build_name: "{{ inventory_file }}"
    startit: "{{ lookup('current_build', build_name, 'SET') }}"
  tasks:
    - debug: msg="Start it - {{ startit }}"
      run_once: true

- hosts: django-app-server
  vars:
    build_name: "{{ inventory_file }}"
    current_build_value: "{{ lookup('current_build', build_name, 'get') }}"
    files_dir: "{{ lookup('env', 'ANSIBLE_FILES')|default('/data/ansible/aca-builds/files', true) }}"
    acting_user: "{{ lookup('env', 'USER') }}"
  tasks:
    - debug: msg="GET it - {{ current_build_value }}"
  roles:
    - { role: "django_app_server_role" }

- hosts: mysql-db-server
  roles:
    - { role: "mysql_db_role" }
  vars:
    files_dir: "{{ lookup('env', 'ANSIBLE_FILES')|default('/data/ansible/aca-builds/files', true) }}"
    acting_user: "{{ lookup('env', 'USER') }}"

# Somewhat customized version of django-app-server - adds nagios server configuration
- hosts: nagios-app-server
  roles:
    - { role: "nagios_app_server_role" }
  vars:
    build_name: "{{ inventory_file }}"
    current_build_value: "{{ lookup('current_build', build_name, 'get') }}"
    files_dir: "{{ lookup('env', 'ANSIBLE_FILES')|default('/data/ansible/aca-builds/files', true) }}"
    acting_user: "{{ lookup('env', 'USER') }}"


