- name: Create the directory structure for the app to live in
  hosts: all

  vars:
    build_name: "{{ inventory_file }}"
    current_build_value: "{{ lookup('current_build', build_name) }}"
    files_dir: "{{ lookup('env', 'ANSIBLE_FILES')|default('/data/ansible/aca-builds/files', true) }}"
    acting_user: "{{ lookup('env', 'USER') }}"

  tasks:
    - include: includes/django-managed-pre-checkout.yml

    - git: repo={{git_repository}} dest={{ base_dir }}/builds/{{ current_build_value }} version={{git_version}}

    - include: includes/django-managed-post-checkout.yml
    - include: includes/nagios_registration.yml
