- hosts: all
  vars:
    files_dir: "{{ lookup('env', 'ANSIBLE_FILES')|default('/data/ansible/aca-builds/files', true) }}"
    acting_user: "{{ lookup('env', 'USER') }}"
  tasks:
    - include: includes/nagios_registration.yml

- hosts: mysql-db-server
  vars:
    files_dir: "{{ lookup('env', 'ANSIBLE_FILES')|default('/data/ansible/aca-builds/files', true) }}"
    acting_user: "{{ lookup('env', 'USER') }}"
  tasks:
    - include: includes/nagios_registration_mysql.yml
